### ISSUE TITLE
Can't run iOS project

### ISSUE THREAD

**Issue by artemsorochan** [AnnonAU/flutter_mapbox_turn_by_turn#2]
I have an issue while running iOS example project
<img width="882" alt="Screenshot 2022-12-02 at 00 02 26" src="https://user-images.githubusercontent.com/116367489/205245780-588482be-094b-4ccb-925e-849425592e78.png">
Is the library ready for the usage or not yet?
Thanks in advance!

**Comment by josephcrowell** [comment]
This is not a released project and has not been published to pub.dev yet
