### ISSUE TITLE
Router build/select/navigate | clean improvement?

### ISSUE THREAD

**Issue by aleonnet** [AnnonAU/flutter_mapbox_turn_by_turn#5]
Hi @josephcrowell 
I've been playing around with some code for Navigation and yours are awesome and customizable.

Unfortunately I think there's no method* to build, choose from alternatives and then start navigation or clear the routes.
Are you planning to add it by now?

This is my first attempt, but using other plugins not so good as yours.

![IMG_0ED2ED7F961D-1](https://github.com/ComputerlinkAU/flutter_mapbox_turn_by_turn/assets/20618327/a4c82ca0-b140-4892-8f1b-587d77d4da6a)

(*)
      switch call.method {
      case "startNavigation":
        strongSelf.startNavigation(arguments: arguments)
      case "stopNavigation":
        if strongSelf.navigationViewController != nil {
          strongSelf.navigationViewControllerDidDismiss(
            strongSelf.navigationViewController!, byCanceling: true)
        }
      case "addOfflineMap":
        strongSelf.addOfflineMap(arguments: arguments)
      case "toggleMuted":
        break
      default:
        result("method is not implemented")
      }

    override fun onMethodCall(methodCall: MethodCall, result: MethodChannel.Result) {
        when (methodCall.method) {
            "startNavigation" -> {
                startNavigation(methodCall)
            }
            "stopNavigation" -> {
                clearRouteAndStopNavigation()
            }
            "addOfflineMap" -> {
                addOfflineMap(methodCall)
            }
            "toggleMuted" -> {
                toggleMuted()
            }
            else -> result.notImplemented()
        }
    }

**Comment by josephcrowell** [comment]
stopNavigation clears the route,  but no I haven't done any code for choosing alternative routes. You seem to have a good handle on how it works, so if you want to submit a pull request that lets you choose routes, I would be more than happy to accept it. My use case is focused on multiple deliveries where the most optimal route is set, so I haven't been pushing development in that direction.

**Comment by aleonnet** [comment]
I see, in my case there may be safety concerns on any optimal route generated, so the user may eventually choose. I'll take a look on the code. Thanks!

**Comment by josephcrowell** [comment]
I would suggest a different set of methods. My start navigation gets the optimal route and starts navigation to it. You would want a showRoutes method to the endpoint coordinates. Then call startNavigationWithChosen endpoint on button click.

**Comment by aleonnet** [comment]
> I would suggest a different set of methods. My start navigation gets the optimal route and starts navigation to it. You would want a showRoutes method to the endpoint coordinates. Then call startNavigationWithChosen endpoint on button click.

I'll try that, thank you! One more thing, I'd like to capture the events that goes on the top banner(like nextInstruction) and maybe the speed limit, do you have any suggestion/recommendation?
![CleanShot 2023-11-14 at 16 28 29](https://github.com/ComputerlinkAU/flutter_mapbox_turn_by_turn/assets/20618327/836117a0-8109-4569-a120-6acc3c8d5b7e)

**Comment by josephcrowell** [comment]
https://github.com/ComputerlinkAU/flutter_mapbox_turn_by_turn/blob/main/android/src/main/kotlin/au/com/annon/flutter_mapbox_turn_by_turn/ui/TurnByTurnNative.kt line 42 sends an event through to Flutter from android when the progress data has changed. it includes the new turn instruction and other data. it's fired from the progress observer.

**Comment by aleonnet** [comment]
I was able to get some progress on iOS, also got some data from the route progress class. Thanks.
![CleanShot 2023-11-16 at 21 35 53](https://github.com/ComputerlinkAU/flutter_mapbox_turn_by_turn/assets/20618327/612801be-3762-40ac-9890-afe7fb3469f0)
![IMG_2468](https://github.com/ComputerlinkAU/flutter_mapbox_turn_by_turn/assets/20618327/90e0bf99-a766-43d5-9013-5791f74f1af2)

**Comment by josephcrowell** [comment]
I wanted to get the iOS version functioning more like the Android version but the client lost interest in iOS on my project. If you make any progress on iOS, please do a pull request asap.

**Comment by aleonnet** [comment]
I ended up using eopeter plugin because its iOS/Android features are more on pair with each other. I had to customize tap gesture routes information call back, switching from embedded to full screen navigation and more progress events.
